### PR TITLE
Use official APT repo.

### PR DESCRIPTION
**Pull request by jezdez**
See http://www.elasticsearch.org/blog/apt-and-yum-repositories/ for more info.

### CODE REVIEW

**Comment by jezdez** [comment]
Using `service elasticsearch start` is just a workaround right now, I don't want to work around all the things done in the package and yet I need to make sure CMD doesn't return directly. Any idea how to do that?

**Comment by jezdez** [comment]
Okay, so this uses a modified version of the init script to start the es binary. This is along the lines of the docker-postgresql repo of yours.

**Comment by bfirsh** [comment]
The reason I used the tarball is because trying to run the .deb outside of an init script is a complete faff. Perhaps it might be simpler if we included bin/elasticsearch from the tarball in this repo? But then we may as well just use the tarball, so I'm not sure.

What advantages do we get from using the Debian package?

**Comment by bfirsh** [comment]
It isn't run as root. That's good. In fact I'd class that as a bug in my dockerfile.

**Comment by jezdez** [comment]
@bfirsh I'm new to docker so forgive my lack of practice with writing good Dockerfiles, this may be all wrong :)

The main advantage for using the deb package I think is not having to update the `Dockerfile` all the time when a new version comes out. I know it sounds like I'm lazy (I am) but it's also a issue with security yada yada. The deb also creates an own elasticsearch user and puts files in locations that one would expect from a Ubuntu based system. In other words, it follows more of the Debian community standards.

I looked into other Dockerfiles for Elasticsearch on Github and found basically every version of it. Using the init system for a single process containers rubs me wrong, indeed. That's how I ended up stripping the official init script of the non-start sections.

**Comment by jezdez** [comment]
Forgot to not use `ulimit` in the start script because that's not supposed to be done inside of Docker guests (right?).

**Comment by bfirsh** [comment]
Setting the version in the Dockerfile is a good thing. It means you can deterministically generate images for a specific version. E.g. I'm also maintaining a 0.90.5 version of this image:

https://github.com/orchardup/docker-elasticsearch/compare/master...0.90.5

You're right, Debian packages are a good thing, but in this case ElasticSearch messed up because they don't include a proper binary in the package. `bin/elasticsearch` from the tarball should be in the Debian package, then this would work properly. Grrr.

**Comment by bfirsh** [comment]
Okay setting the separate tag is broken, so I think you're right on this one. Thanks!

**Pull request merged**
